# Generated by Django 5.2.3 on 2025-06-20 18:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_fan', models.CharField(max_length=100, unique=True, verbose_name='Nama Fan')),
                ('deskripsi', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Santri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=150)),
                ('id_santri', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='ID Santri')),
                ('status', models.CharField(choices=[('Aktif', 'Aktif'), ('Lulus', 'Lulus'), ('Non-Aktif', 'Non-Aktif')], default='Aktif', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SKS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_sks', models.CharField(max_length=200, unique=True, verbose_name='Nama SKS/Kitab')),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sks_list', to='core.fan')),
            ],
            options={
                'verbose_name': 'SKS',
                'verbose_name_plural': 'SKS',
            },
        ),
        migrations.CreateModel(
            name='RiwayatTes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_tes', models.DateField()),
                ('nilai', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('santri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_tes', to='core.santri')),
                ('sks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_tes', to='core.sks')),
            ],
        ),
    ]
