# Generated by Django 5.2.3 on 2025-06-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fan',
            name='urutan',
            field=models.IntegerField(default=0, help_text='Isi dengan angka untuk urutan, misal: 1, 2, 3...'),
        ),
    ]
