# Generated by Django 5.2.3 on 2025-06-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fan_urutan'),
    ]

    operations = [
        migrations.AddField(
            model_name='fan',
            name='target_durasi_hari',
            field=models.PositiveIntegerField(default=30, help_text='Target penyelesaian dalam HARI, misal: 1 bulan = 30 hari'),
        ),
    ]
