# Generated by Django 5.2.3 on 2025-06-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_fan_target_durasi_hari'),
    ]

    operations = [
        migrations.AddField(
            model_name='sks',
            name='nilai_minimal',
            field=models.PositiveIntegerField(default=90, help_text='Nilai minimal untuk lulus SKS ini'),
        ),
    ]
