# Generated by Django 5.2.3 on 2025-06-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sks_nilai_minimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='santri',
            name='foto_profil',
            field=models.ImageField(blank=True, help_text='Upload foto profil santri', null=True, upload_to='santri_photos/'),
        ),
    ]
