# Generated by Django 5.2.3 on 2025-06-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ubah_status_lulus_ke_pengurus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengurus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=150, verbose_name='Nama Lengkap')),
                ('jabatan', models.CharField(blank=True, max_length=100, verbose_name='Jabatan')),
                ('alamat_kabupaten', models.CharField(blank=True, max_length=100, verbose_name='Kabupaten/Kota')),
                ('alamat_provinsi', models.CharField(blank=True, max_length=100, verbose_name='Provinsi')),
                ('nomor_whatsapp', models.CharField(blank=True, help_text='Gunakan format internasional, contoh: 6281234567890', max_length=20)),
                ('foto_profil', models.ImageField(blank=True, null=True, upload_to='pengurus_photos/')),
            ],
            options={
                'verbose_name': 'Pengurus',
                'verbose_name_plural': 'Pengurus',
            },
        ),
        migrations.AlterModelOptions(
            name='fan',
            options={'verbose_name': 'Fan', 'verbose_name_plural': 'Fan'},
        ),
        migrations.AlterModelOptions(
            name='riwayattes',
            options={'verbose_name': 'Riwayat Tes', 'verbose_name_plural': 'Riwayat Tes'},
        ),
        migrations.AlterModelOptions(
            name='santri',
            options={'verbose_name': 'Santri', 'verbose_name_plural': 'Santri'},
        ),
        migrations.AlterField(
            model_name='santri',
            name='status',
            field=models.CharField(choices=[('Aktif', 'Aktif'), ('Pengurus', 'Pengurus/Abdi Dalem'), ('Non-Aktif', 'Non-Aktif')], default='Aktif', max_length=10),
        ),
    ]
