# Generated by Django 5.2.3 on 2025-06-25 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pengurus_alter_fan_options_alter_riwayattes_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fan',
            options={},
        ),
        migrations.AlterModelOptions(
            name='riwayattes',
            options={},
        ),
        migrations.AlterModelOptions(
            name='santri',
            options={},
        ),
        migrations.RemoveField(
            model_name='fan',
            name='deskripsi',
        ),
        migrations.AddField(
            model_name='santri',
            name='alamat_kabupaten',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kabupaten/Kota'),
        ),
        migrations.AddField(
            model_name='santri',
            name='alamat_provinsi',
            field=models.CharField(blank=True, max_length=100, verbose_name='Provinsi'),
        ),
        migrations.AddField(
            model_name='santri',
            name='kamar',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='santri',
            name='kelas_sekolah',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kelas Sekolah Formal'),
        ),
        migrations.AddField(
            model_name='santri',
            name='pembimbing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='santri_bimbingan', to='core.pengurus'),
        ),
        migrations.AlterField(
            model_name='santri',
            name='foto_profil',
            field=models.ImageField(blank=True, null=True, upload_to='santri_photos/'),
        ),
        migrations.AlterField(
            model_name='santri',
            name='status',
            field=models.CharField(choices=[('Aktif', 'Santri Aktif'), ('Pengurus', 'Pengurus/Abdi Dalem'), ('Non-Aktif', 'Non-Aktif/Lulusan')], default='Aktif', max_length=10),
        ),
    ]
