# Generated by Django 5.2.3 on 2025-06-26 23:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_fan_options_alter_riwayattes_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riwayattes',
            options={'ordering': ['-tanggal_pelaksanaan', '-id']},
        ),
        migrations.AlterModelOptions(
            name='santri',
            options={'ordering': ['nama_lengkap']},
        ),
        migrations.RenameField(
            model_name='riwayattes',
            old_name='tanggal_tes',
            new_name='tanggal_pelaksanaan',
        ),
        migrations.AddField(
            model_name='riwayattes',
            name='penguji',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tes_diuji', to='core.pengurus'),
        ),
        migrations.AddField(
            model_name='riwayattes',
            name='status_tes',
            field=models.CharField(choices=[('Terdaftar', 'Terdaftar'), ('Selesai', 'Selesai'), ('Batal', 'Batal')], default='Terdaftar', max_length=10),
        ),
        migrations.AddField(
            model_name='riwayattes',
            name='tanggal_pendaftaran',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='riwayattes',
            name='nilai',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='santri',
            name='status',
            field=models.CharField(choices=[('Aktif', 'Santri Aktif'), ('Pengurus', 'Pengurus/Abdi Dalem'), ('Non-Aktif', 'Non-Aktif/Lulusan')], default='Aktif', max_length=20),
        ),
    ]
