# Generated by Django 5.2.3 on 2025-06-27 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_riwayattes_options_alter_santri_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupKontak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_grup', models.CharField(max_length=100, verbose_name='Nama Grup Kontak')),
                ('urutan', models.PositiveIntegerField(default=0, help_text='Grup dengan urutan lebih kecil akan tampil lebih dulu.')),
            ],
            options={
                'verbose_name': 'Grup Kontak',
                'verbose_name_plural': 'Grup Kontak',
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='KontakPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=150)),
                ('keterangan', models.CharField(help_text='Contoh: Admin Pendaftaran, Informasi Umum', max_length=150)),
                ('nomor_whatsapp', models.CharField(blank=True, help_text='Format: 6281234567890', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('foto_profil', models.ImageField(blank=True, null=True, upload_to='kontak_photos/')),
                ('grup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kontak_list', to='core.grupkontak')),
            ],
            options={
                'verbose_name': 'Kontak Person',
                'verbose_name_plural': 'Kontak Person',
                'ordering': ['nama_lengkap'],
            },
        ),
    ]
