# Generated by Django 5.2.3 on 2025-06-28 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_grupkontak_kontakperson'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asrama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_asrama', models.CharField(max_length=150, unique=True, verbose_name='Nama Asrama')),
                ('id_asrama_unik', models.CharField(help_text='ID unik untuk login, contoh: takhossus_pusat', max_length=50, unique=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Data Asrama',
                'verbose_name_plural': 'Data Asrama',
            },
        ),
        migrations.RemoveField(
            model_name='pengurus',
            name='alamat_kabupaten',
        ),
        migrations.RemoveField(
            model_name='pengurus',
            name='alamat_provinsi',
        ),
        migrations.RemoveField(
            model_name='santri',
            name='alamat_kabupaten',
        ),
        migrations.RemoveField(
            model_name='santri',
            name='alamat_provinsi',
        ),
        migrations.RemoveField(
            model_name='santri',
            name='kamar',
        ),
        migrations.RemoveField(
            model_name='santri',
            name='kelas_sekolah',
        ),
        migrations.AlterField(
            model_name='fan',
            name='nama_fan',
            field=models.CharField(max_length=100, verbose_name='Nama Fan'),
        ),
        migrations.AlterField(
            model_name='grupkontak',
            name='urutan',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kontakperson',
            name='keterangan',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='kontakperson',
            name='nomor_whatsapp',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='sks',
            name='nama_sks',
            field=models.CharField(max_length=200, verbose_name='Nama SKS/Kitab'),
        ),
        migrations.AddField(
            model_name='fan',
            name='asrama',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fans', to='core.asrama'),
        ),
        migrations.AddField(
            model_name='grupkontak',
            name='asrama',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grup_kontak_list', to='core.asrama'),
        ),
        migrations.AddField(
            model_name='kontakperson',
            name='asrama',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kontak_person_list', to='core.asrama'),
        ),
        migrations.AddField(
            model_name='pengurus',
            name='asrama',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pengurus_list', to='core.asrama'),
        ),
        migrations.AddField(
            model_name='riwayattes',
            name='asrama',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tes_list', to='core.asrama'),
        ),
        migrations.AddField(
            model_name='santri',
            name='asrama',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='santri_list', to='core.asrama'),
        ),
        migrations.AddField(
            model_name='sks',
            name='asrama',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sks_list', to='core.asrama'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asrama', models.ForeignKey(blank=True, help_text='Asrama tempat user ini bertugas. Kosongkan untuk superuser.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.asrama')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
