# Generated by Django 5.2.3 on 2025-06-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_asrama_remove_pengurus_alamat_kabupaten_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asrama',
            options={'ordering': ['nama_asrama'], 'verbose_name': 'Data Asrama', 'verbose_name_plural': 'Data Asrama'},
        ),
        migrations.AlterModelOptions(
            name='fan',
            options={'ordering': ['urutan']},
        ),
        migrations.AlterModelOptions(
            name='pengurus',
            options={'ordering': ['nama_lengkap'], 'verbose_name': 'Pengurus', 'verbose_name_plural': 'Pengurus'},
        ),
        migrations.AlterModelOptions(
            name='sks',
            options={'ordering': ['fan__urutan', 'nama_sks'], 'verbose_name': 'SKS', 'verbose_name_plural': 'SKS'},
        ),
        migrations.AddField(
            model_name='asrama',
            name='kata_pengantar',
            field=models.TextField(blank=True, null=True, verbose_name='Kata Pengantar Singkat'),
        ),
        migrations.AddField(
            model_name='asrama',
            name='link_instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Link Instagram'),
        ),
        migrations.AddField(
            model_name='asrama',
            name='link_tiktok',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Link TikTok'),
        ),
        migrations.AddField(
            model_name='asrama',
            name='link_whatsapp',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Link WhatsApp (wa.me)'),
        ),
        migrations.AddField(
            model_name='asrama',
            name='link_youtube',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Link YouTube'),
        ),
        migrations.AddField(
            model_name='asrama',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='asrama_logos/', verbose_name='Logo Asrama'),
        ),
    ]
