# Generated by Django 5.2.3 on 2025-07-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_asrama_options_alter_fan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengurus',
            name='alamat_kabupaten',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kabupaten/Kota'),
        ),
        migrations.AddField(
            model_name='pengurus',
            name='alamat_provinsi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Provinsi'),
        ),
        migrations.AddField(
            model_name='santri',
            name='alamat_kabupaten',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kabupaten/Kota'),
        ),
        migrations.AddField(
            model_name='santri',
            name='alamat_provinsi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Provinsi'),
        ),
        migrations.AddField(
            model_name='santri',
            name='kamar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='santri',
            name='kelas_sekolah',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kelas Sekolah Formal'),
        ),
    ]
